services:
  - type: web
    name: med-promocoes-backend
    env: docker
    plan: free
    buildCommand: docker build -t med-promocoes-backend .
    startCommand: node backend/src/app.js
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 0.5